---

- hosts: all
  become: true
  tasks:

  - name: update the cache , install the apache and its php support packages
    package: #generic package manager that runs the right package manager for each os
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
